name: ✨ Feature Request

description: Suggest a feature or idea that you would like to see in TNM HR Platform

title: "[Feature] <title>"
labels: [enhancement, v5, needs triage]
assignees: ""

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this feature?
      description: Please search to see if an issue already exists for the feature you requested.
      options:
        - label: Yes, I have searched the existing issues and it doesn't exist.
          required: true

  - type: textarea
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see in TNM HR Platform and the problem it would solve.
    validations:
      required: true
